/*点评商户维度表*/
select
    dp_shop_id,
    dp_shop_name,
    mt_main_poi_id,
    dp_city_id,
    dp_city_name,
    dp_province_id,
    dp_province_name,
    dp_district_id,
    dp_district_name,
    dp_shop_first_cate_id,
    dp_shop_first_cate_name,
    dp_shop_second_cate_id,
    dp_shop_second_cate_name,
    dp_shop_address,
    latitude,
    longitude
from
    dw.dim_dp_shop
