/*销售计划维表*/
select
    salesplan_id,
    salesplan_name,
    shop_id,
    category_id,
    category_name,
    show_starttime,
    performance_id,
    performance_name,
    show_id,
    show_name,
    ticketclass_id,
    ticket_price,
    salesplan_ontime,
    salesplan_createtime,
    customer_id,
    customer_name,
    customer_type_name,
    customer_lvl1_name,
    shop_name,
    city_name,
    area_1_level_name,
    area_2_level_name,
    province_name,
    setnumber,
    bd_name
from
    mart_movie.dim_myshow_salesplan
where
    1=1
